/*
Storybook: Open Source software for novelists and authors.
Copyright (C) 2008 - 2012 Martin Mustun

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package storybook.model.hbn.entity;

import javax.swing.Icon;

import storybook.toolkit.I18N;

/**
 * Gender generated by hbm2java
 * 
 * @hibernate.class table="GENDER"
 */
public class Gender extends AbstractEntity {

	private String name;
	private Integer childhood;
	private Integer adolescence;
	private Integer adulthood;
	private Integer retirement;

	public Gender() {
		childhood = 12;
		adolescence = 6;
		adulthood = 47;
		retirement = 14;
	}

	public Gender(String name, Integer childhood, Integer adolescence, Integer adulthood, Integer retirement) {
		this.name = name;
		this.childhood = childhood;
		this.adolescence = adolescence;
		this.adulthood = adulthood;
		this.retirement = retirement;
	}

	@Override
	public boolean equals(Object obj) {
		if (!super.equals(obj)) {
			return false;
		}
		Gender test = (Gender) obj;
		boolean ret = true;
		ret = ret && equalsStringNullValue(name, test.getName());
		ret = ret && equalsIntegerNullValue(childhood, test.getChildhood());
		ret = ret && equalsIntegerNullValue(adolescence, test.getAdolescence());
		ret = ret && equalsIntegerNullValue(adulthood, test.getAdulthood());
		ret = ret && equalsIntegerNullValue(retirement, test.getRetirement());
		return ret;
	}

	/**
	 * @hibernate.property not-null="true"
	 */
	public Integer getAdolescence() {
		return this.adolescence;
	}

	/**
	 * @hibernate.property not-null="true"
	 */
	public Integer getAdulthood() {
		return this.adulthood;
	}

	/**
	 * @hibernate.property not-null="true"
	 */
	public Integer getChildhood() {
		return this.childhood;
	}

	@Override
	public Icon getIcon() {
		if (isMale()) {
			return I18N.getIcon("icon.small.man");
		}
		if (isFemale()) {
			return I18N.getIcon("icon.small.woman");
		}
		return I18N.getIcon("icon.small.person");
	}

	/**
	 * @hibernate.id column="ID" generator-class="increment"
	 *               unsaved-value="null"
	 */
	@Override
	public Long getId() {
		return this.id;
	}

	/**
	 * @hibernate.property
	 */
	public String getName() {
		return this.name;
	}

	/**
	 * @hibernate.property not-null="true"
	 */
	public Integer getRetirement() {
		return this.retirement;
	}

	@Override
	public int hashCode() {
		int hash = super.hashCode();
		hash = hash * 31 + (name != null ? name.hashCode() : 0);
		hash = hash * 31 + (childhood != null ? childhood.hashCode() : 0);
		hash = hash * 31 + (adolescence != null ? adolescence.hashCode() : 0);
		hash = hash * 31 + (adulthood != null ? adulthood.hashCode() : 0);
		hash = hash * 31 + (retirement != null ? retirement.hashCode() : 0);
		return hash;
	}

	public boolean isFemale() {
		return id == 2;
	}

	public boolean isMale() {
		return id == 1;
	}

	public void setAdolescence(Integer adolescence) {
		this.adolescence = adolescence;
	}

	public void setAdulthood(Integer adulthood) {
		this.adulthood = adulthood;
	}

	public void setChildhood(Integer childhood) {
		this.childhood = childhood;
	}

	public void setIcon(Icon icon) {
		// ulterieur Gender.setIcon
	}

	public void setId(Long id) {
		this.id = id;
	}

	public void setName(String name) {
		this.name = name;
	}

	public void setRetirement(Integer retirement) {
		this.retirement = retirement;
	}

	@Override
	public String toString() {
		return getName();
	}
}
