/*
Storybook: Open Source software for novelists and authors.
Copyright (C) 2008 - 2012 Martin Mustun

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package storybook.model.hbn.entity;

import storybook.model.state.IdeaState;
import storybook.model.state.IdeaStateModel;
import storybook.toolkit.TextUtil;
import storybook.toolkit.html.HtmlUtil;

// TODO: Auto-generated Javadoc
/**
 * Ideas generated by hbm2java.
 *
 * @hibernate.class table="IDEAS"
 */
public class Idea extends AbstractEntity implements Comparable<Idea> {

	/** The Constant serialVersionUID. */
	private static final long serialVersionUID = -205159153726421959L;
	
	/** The status. */
	private Integer status;
	
	/** The note. */
	private String note;
	
	/** The category. */
	private String category;

	/**
	 * Instantiates a new idea.
	 */
	public Idea() {
	}

	/**
	 * Instantiates a new idea.
	 *
	 * @param status the status
	 * @param note the note
	 * @param category the category
	 */
	public Idea(Integer status, String note, String category) {
		this.status = status;
		this.note = note;
		this.category = category;
	}

	/* (non-Javadoc)
	 * @see java.lang.Comparable#compareTo(java.lang.Object)
	 */
	@Override
	public int compareTo(Idea o) {
		return getNote().compareTo(o.getNote());
	}

	/* (non-Javadoc)
	 * @see storybook.model.hbn.entity.AbstractEntity#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object obj) {
		if (!super.equals(obj)) {
			return false;
		}
		Idea test = (Idea) obj;
		boolean ret = true;
		ret = ret && equalsIntegerNullValue(status, test.getStatus());
		ret = ret && equalsStringNullValue(category, test.getCategory());
		ret = ret && equalsStringNullValue(note, test.getNote());
		return ret;
	}

	/**
	 * Gets the category.
	 *
	 * @return the category
	 * @hibernate.property 
	 */
	public String getCategory() {
		return this.category;
	}

	/**
	 * Gets the id.
	 *
	 * @return the id
	 * @hibernate.id column="ID" generator-class="increment"
	 *               unsaved-value="null"
	 */
	@Override
	public Long getId() {
		return this.id;
	}

	/**
	 * Gets the idea state.
	 *
	 * @return the idea state
	 */
	public IdeaState getIdeaState() {
		IdeaStateModel model = new IdeaStateModel();
		return (IdeaState) model.findByNumber(this.status);
	}

	/**
	 * Gets the note.
	 *
	 * @return the note
	 * @hibernate.property 
	 */
	public String getNote() {
		return this.note;
	}

	/**
	 * Gets the notes.
	 *
	 * @return the notes
	 */
	public String getNotes() {
		return getNote();
	}

	/**
	 * Gets the status.
	 *
	 * @return the status
	 * @hibernate.property 
	 */
	public Integer getStatus() {
		return this.status;
	}

	/* (non-Javadoc)
	 * @see storybook.model.hbn.entity.AbstractEntity#hashCode()
	 */
	@Override
	public int hashCode() {
		int hash = super.hashCode();
		hash = hash * 31 + (status != null ? status.hashCode() : 0);
		hash = hash * 31 + (category != null ? category.hashCode() : 0);
		hash = hash * 31 + (note != null ? note.hashCode() : 0);
		return hash;
	}

	/**
	 * Sets the category.
	 *
	 * @param category the new category
	 */
	public void setCategory(String category) {
		this.category = category;
	}

	/**
	 * Sets the id.
	 *
	 * @param id the new id
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * Sets the idea state.
	 *
	 * @param state the new idea state
	 */
	public void setIdeaState(IdeaState state) {
		this.status = state.getNumber();
	}

	/**
	 * Sets the note.
	 *
	 * @param note the new note
	 */
	public void setNote(String note) {
		this.note = note;
	}

	/**
	 * Sets the notes.
	 *
	 * @param notes the new notes
	 */
	public void setNotes(String notes) {
		setNote(notes);
	}

	/**
	 * Sets the status.
	 *
	 * @param status the new status
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		if (note == null) {
			return category;
		}
		String text = HtmlUtil.htmlToText(note);
		if (category == null || category.isEmpty()) {
			return TextUtil.truncateString(text, 50);
		}
		return category + ": " + TextUtil.truncateString(text, 50);
	}
}
