/*
Storybook: Open Source software for novelists and authors.
Copyright (C) 2008 - 2012 Martin Mustun

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package storybook.model.hbn.entity;

import java.sql.Timestamp;
import java.util.Date;

// TODO: Auto-generated Javadoc
/**
 * Part generated by hbm2java.
 *
 * @hibernate.class table="PART"
 */

public class Part extends AbstractEntity {

	/** The Constant serialVersionUID. */
	private static final long serialVersionUID = -7961818979645701511L;
	
	/** The number. */
	private Integer number;
	
	/** The name. */
	private String name;
	
	/** The notes. */
	private String notes;
	
	/** The superpart. */
	private Part superpart;
	
	/** The creation time. */
	private Timestamp creationTime;
	
	/** The objective time. */
	private Timestamp objectiveTime;
	
	/** The done time. */
	private Timestamp doneTime;
	
	/** The objective chars. */
	private Integer objectiveChars;

	/**
	 * Instantiates a new part.
	 */
	public Part() {
		this.creationTime = new Timestamp(new Date().getTime());
	}

	/**
	 * Instantiates a new part.
	 *
	 * @param number the number
	 * @param name the name
	 * @param notes the notes
	 * @param superpart the superpart
	 * @param creationTime the creation time
	 * @param objectiveTime the objective time
	 * @param doneTime the done time
	 */
	public Part(Integer number, String name, String notes, Part superpart, Timestamp creationTime,
			Timestamp objectiveTime, Timestamp doneTime) {
		this.number = number;
		this.name = name;
		this.notes = notes;
		this.superpart = superpart;
		this.creationTime = creationTime;
		this.objectiveTime = objectiveTime;
		this.doneTime = doneTime;
	}

	/* (non-Javadoc)
	 * @see storybook.model.hbn.entity.AbstractEntity#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object obj) {
		if (!super.equals(obj)) {
			return false;
		}
		Part test = (Part) obj;
		boolean ret = true;
		ret = ret && equalsIntegerNullValue(number, test.getNumber());
		ret = ret && equalsStringNullValue(name, test.getName());
		ret = ret && equalsStringNullValue(notes, test.getNotes());
		ret = ret && equalsObjectNullValue(superpart, test.getSuperpart());
		return ret;
	}

	/**
	 * Gets the creation time.
	 *
	 * @return the creation time
	 */
	public Timestamp getCreationTime() {
		return creationTime;
	}

	/**
	 * Gets the done time.
	 *
	 * @return the done time
	 */
	public Timestamp getDoneTime() {
		return doneTime;
	}

	/**
	 * Gets the id.
	 *
	 * @return the id
	 * @hibernate.id column="ID" generator-class="increment"
	 *               unsaved-value="null"
	 */
	@Override
	public Long getId() {
		return this.id;
	}

	/**
	 * Gets the name.
	 *
	 * @return the name
	 * @hibernate.property 
	 */
	public String getName() {
		return this.name;
	}

	/**
	 * Gets the notes.
	 *
	 * @return the notes
	 * @hibernate.property 
	 */
	public String getNotes() {
		return this.notes;
	}

	/**
	 * Gets the number.
	 *
	 * @return the number
	 * @hibernate.property 
	 */
	public Integer getNumber() {
		return this.number;
	}

	/**
	 * Gets the number name.
	 *
	 * @return the number name
	 */
	public String getNumberName() {
		return this.number + ": " + this.name;
	}

	/**
	 * Gets the objective chars.
	 *
	 * @return the objective chars
	 */
	public Integer getObjectiveChars() {
		return (hasObjectiveChars()) ? this.objectiveChars : 0;
	}

	/**
	 * Gets the objective time.
	 *
	 * @return the objective time
	 */
	public Timestamp getObjectiveTime() {
		return objectiveTime;
	}

	/**
	 * Gets the superpart.
	 *
	 * @return the superpart
	 * @hibernate.property 
	 */
	public Part getSuperpart() {
		return this.superpart;
	}

	/**
	 * Checks for creation time.
	 *
	 * @return true, if successful
	 * @hibernate.property 
	 */
	public boolean hasCreationTime() {
		return creationTime != null;
	}

	/**
	 * Checks for done time.
	 *
	 * @return true, if successful
	 */
	public boolean hasDoneTime() {
		return doneTime != null;
	}

	/* (non-Javadoc)
	 * @see storybook.model.hbn.entity.AbstractEntity#hashCode()
	 */
	@Override
	public int hashCode() {
		int hash = super.hashCode();
		hash = hash * 31 + (number != null ? number.hashCode() : 0);
		hash = hash * 31 + (name != null ? name.hashCode() : 0);
		hash = hash * 31 + (notes != null ? notes.hashCode() : 0);
		hash = hash * 31 + (superpart != null ? superpart.hashCode() : 0);
		return hash;
	}

	/**
	 * Checks for objective chars.
	 *
	 * @return true, if successful
	 * @hibernate.property 
	 */
	public boolean hasObjectiveChars() {
		return objectiveChars != null;
	}

	/**
	 * Checks for objective time.
	 *
	 * @return true, if successful
	 * @hibernate.property 
	 */
	public boolean hasObjectiveTime() {
		return objectiveTime != null;
	}

	/**
	 * Checks for superpart.
	 *
	 * @return true, if successful
	 */
	public boolean hasSuperpart() {
		return superpart != null;
	}

	/**
	 * Checks if is done.
	 *
	 * @return true, if is done
	 * @hibernate.property 
	 */
	public boolean isDone() {
		return hasDoneTime();
	}

	/**
	 * Checks if is part of part.
	 *
	 * @param ancestor the ancestor
	 * @return true, if is part of part
	 */
	public boolean isPartOfPart(Part ancestor) {
		if (this.getId().equals(ancestor.getId())) {
			return true;
		}
		if (this.hasSuperpart()) {
			return this.getSuperpart().isPartOfPart(ancestor);
		}
		return false;
	}

	/**
	 * Sets the creation time.
	 *
	 * @param ts the new creation time
	 */
	public void setCreationTime(Timestamp ts) {
		creationTime = ts;
	}

	/**
	 * Sets the done time.
	 *
	 * @param ts the new done time
	 */
	public void setDoneTime(Timestamp ts) {
		doneTime = ts;
	}

	/**
	 * Sets the id.
	 *
	 * @param id the new id
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * Sets the name.
	 *
	 * @param name the new name
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * Sets the notes.
	 *
	 * @param notes the new notes
	 */
	public void setNotes(String notes) {
		this.notes = notes;
	}

	/**
	 * Sets the number.
	 *
	 * @param number the new number
	 */
	public void setNumber(Integer number) {
		this.number = number;
	}

	/**
	 * Sets the objective chars.
	 *
	 * @param objectiveChars the new objective chars
	 */
	public void setObjectiveChars(Integer objectiveChars) {
		this.objectiveChars = objectiveChars;
	}

	/**
	 * Sets the objective time.
	 *
	 * @param ts the new objective time
	 */
	public void setObjectiveTime(Timestamp ts) {
		objectiveTime = ts;
	}

	/**
	 * Sets the superpart.
	 *
	 * @param superpart the new superpart
	 */
	public void setSuperpart(Part superpart) {
		this.superpart = superpart;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		return getNumber() + ": " + getName();
	}
}
