/*
Storybook: Open Source software for novelists and authors.
Copyright (C) 2008 - 2012 Martin Mustun

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package storybook.model.hbn.entity;

import java.sql.Timestamp;
import java.text.SimpleDateFormat;

import storybook.model.state.TimeStepState;
import storybook.model.state.TimeStepStateModel;
import storybook.toolkit.TextUtil;

// TODO: Auto-generated Javadoc
/**
 * TimeEvent generated by hbm2java.
 *
 * @hibernate.class table="TIMEEVENT"
 */

public class TimeEvent extends AbstractEntity implements Comparable<TimeEvent> {

	/** The Constant serialVersionUID. */
	private static final long serialVersionUID = -834830970281060010L;
	
	/** The title. */
	private String title;
	
	/** The notes. */
	private String notes;
	
	/** The event time. */
	private Timestamp eventTime;
	
	/** The time step. */
	private Integer timeStep;
	
	/** The category. */
	private String category;

	/**
	 * Instantiates a new time event.
	 */
	public TimeEvent() {
	}

	/**
	 * Instantiates a new time event.
	 *
	 * @param title the title
	 * @param notes the notes
	 * @param eventTime the event time
	 * @param timeStep the time step
	 * @param category the category
	 */
	public TimeEvent(String title, String notes, Timestamp eventTime, Integer timeStep, String category) {
		this.title = title;
		this.notes = notes;
		this.eventTime = eventTime;
		this.timeStep = timeStep;
		this.timeStep = timeStep;
		this.category = category;
	}

	/* (non-Javadoc)
	 * @see java.lang.Comparable#compareTo(java.lang.Object)
	 */
	@Override
	public int compareTo(TimeEvent ch) {
		if (eventTime == null) {
			return title.compareTo(ch.title);
		} else {
			return eventTime.compareTo(ch.eventTime);
		}
	}

	/* (non-Javadoc)
	 * @see storybook.model.hbn.entity.AbstractEntity#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object obj) {
		if (!super.equals(obj)) {
			return false;
		}
		TimeEvent test = (TimeEvent) obj;
		boolean ret = true;
		ret = ret && equalsStringNullValue(title, test.getTitle());
		ret = ret && equalsStringNullValue(notes, test.getNotes());
		ret = ret && equalsObjectNullValue(eventTime, test.getEventTime());
		return ret;
	}

	/**
	 * Gets the category.
	 *
	 * @return the category
	 */
	public String getCategory() {
		return this.category;
	}

	/**
	 * Gets the event time.
	 *
	 * @return the event time
	 */
	public Timestamp getEventTime() {
		return (hasEventTime() ? eventTime : new Timestamp(0));
	}

	/**
	 * Gets the id.
	 *
	 * @return the id
	 * @hibernate.id column="ID" generator-class="increment"
	 *               unsaved-value="null"
	 */
	@Override
	public Long getId() {
		return this.id;
	}

	/**
	 * Gets the notes.
	 *
	 * @return the notes
	 * @hibernate.property 
	 */
	public String getNotes() {
		if (notes == null) {
			return "";
		}
		return this.notes;
	}

	/**
	 * Gets the step format.
	 *
	 * @return the step format
	 */
	public String getStepFormat() {
		switch (getTimeStep().intValue()) {
		case 0:
			return "yyyy-MM-dd HH:mm";
		case 1:
			return "yyyy-MM-dd HH";
		case 2:
			return "yyyy-MM-dd";
		case 3:
			return "yyyy-MM";
		default:
			return "yyyy";
		}
	}

	/**
	 * Gets the time step.
	 *
	 * @return the time step
	 */
	public Integer getTimeStep() {
		return this.timeStep;
	}

	/**
	 * Gets the time step state.
	 *
	 * @return the time step state
	 */
	public TimeStepState getTimeStepState() {
		TimeStepStateModel model = new TimeStepStateModel();
		return (TimeStepState) model.findByNumber(this.timeStep);
	}

	/**
	 * Gets the title.
	 *
	 * @return the title
	 * @hibernate.property 
	 */
	public String getTitle() {
		return this.title == null ? "" : this.title;
	}

	/**
	 * Gets the title.
	 *
	 * @param truncate the truncate
	 * @return the title
	 */
	public String getTitle(boolean truncate) {
		return title == null ? "" : TextUtil.truncateString(title, 30);
	}

	/**
	 * Checks for event time.
	 *
	 * @return true, if successful
	 * @hibernate.property 
	 */
	public boolean hasEventTime() {
		return eventTime != null;
	}

	/* (non-Javadoc)
	 * @see storybook.model.hbn.entity.AbstractEntity#hashCode()
	 */
	@Override
	public int hashCode() {
		int hash = super.hashCode();
		if (title != null) {
			hash = hash * 31 + title.hashCode();
		}
		if (notes != null) {
			hash = hash * 31 + notes.hashCode();
		}
		if (eventTime != null) {
			hash = hash * 31 + eventTime.hashCode();
		}
		return hash;
	}

	/**
	 * Sets the category.
	 *
	 * @param category the new category
	 */
	public void setCategory(String category) {
		this.category = (category == null ? "" : category);
	}

	/**
	 * Sets the event time.
	 *
	 * @param ts the new event time
	 */
	public void setEventTime(Timestamp ts) {
		eventTime = ts;
	}

	/**
	 * Sets the id.
	 *
	 * @param id the new id
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * Sets the notes.
	 *
	 * @param notes the new notes
	 */
	public void setNotes(String notes) {
		this.notes = notes;
	}

	/**
	 * Sets the time step.
	 *
	 * @param state the new time step
	 * @hibernate.property 
	 */
	public void setTimeStep(Integer state) {
		this.timeStep = state;
	}

	/**
	 * Sets the time step state.
	 *
	 * @param state the new time step state
	 */
	public void setTimeStepState(TimeStepState state) {
		this.timeStep = state.getNumber();
	}

	/**
	 * Sets the title.
	 *
	 * @param title the new title
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		if (isTransient()) {
			return "";
		}
		SimpleDateFormat format = new SimpleDateFormat(getStepFormat());
		String time = format.format(getEventTime());
		return time + " - " + getTitle();
	}

}
